// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPQz2zHFzEuOnSYbYsbLdeE-EHndmVk-g',
    appId: '1:726976321813:web:063c8d91e7adcc9fc3711c',
    messagingSenderId: '726976321813',
    projectId: 'mad-project-5e5be',
    authDomain: 'mad-project-5e5be.firebaseapp.com',
    databaseURL: 'https://mad-project-5e5be-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mad-project-5e5be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7lC7WVC5yi-fxIyw3mMgPZuPo5zVhG-A',
    appId: '1:726976321813:android:2b90d827956fcb07c3711c',
    messagingSenderId: '726976321813',
    projectId: 'mad-project-5e5be',
    databaseURL: 'https://mad-project-5e5be-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mad-project-5e5be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSfbupgTLDF8XCKLmtN4E4R8vOh7mmxBU',
    appId: '1:726976321813:ios:3b5ea4147e232c25c3711c',
    messagingSenderId: '726976321813',
    projectId: 'mad-project-5e5be',
    databaseURL: 'https://mad-project-5e5be-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mad-project-5e5be.appspot.com',
    iosBundleId: 'upm.mad.flutter.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSfbupgTLDF8XCKLmtN4E4R8vOh7mmxBU',
    appId: '1:726976321813:ios:3b5ea4147e232c25c3711c',
    messagingSenderId: '726976321813',
    projectId: 'mad-project-5e5be',
    databaseURL: 'https://mad-project-5e5be-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mad-project-5e5be.appspot.com',
    iosBundleId: 'upm.mad.flutter.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPQz2zHFzEuOnSYbYsbLdeE-EHndmVk-g',
    appId: '1:726976321813:web:d2e6cdb396cfa82ac3711c',
    messagingSenderId: '726976321813',
    projectId: 'mad-project-5e5be',
    authDomain: 'mad-project-5e5be.firebaseapp.com',
    databaseURL: 'https://mad-project-5e5be-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mad-project-5e5be.appspot.com',
  );
}
